-- 002: AI social-media captions on videos.
-- Run once in the Supabase SQL editor, after 001_init.sql.
--
-- A caption (one line + hashtags) is generated by Gemini when a video is
-- approved. caption_status tracks the async generation lifecycle.

alter table videos add column if not exists caption text;
alter table videos add column if not exists hashtags text[];
alter table videos add column if not exists caption_status text not null default 'none';
alter table videos add column if not exists caption_error text;

-- Constrain caption_status to the known lifecycle values.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'videos_caption_status_check'
  ) then
    alter table videos
      add constraint videos_caption_status_check
      check (caption_status in ('none', 'generating', 'ready', 'error'));
  end if;
end $$;
